# -*- coding: utf-8 -*-
"""Cardiovascular Disease.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rinOzuw4mgolbm5Td8Yft72H5JxNYahb
"""

from google.colab import files
files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn

df=pd.read_csv('cardio_train.csv', sep=';')

df

df['cardio'].value_counts()

seaborn.countplot(df['cardio'])

df.isnull().sum()

df.isnull().values.any()

seaborn.countplot(x='gender', hue='cardio',data=df, palette='colorblind', edgecolor=seaborn.color_palette('dark', n_colors=1))

df=df.drop(['id'],axis=1)

df

seaborn.countplot(x='gender', hue='cardio',data=df, palette='colorblind', edgecolor=seaborn.color_palette('dark', n_colors=1))

seaborn.countplot(x='age', hue='cardio', data=df, palette='colorblind', edgecolor=seaborn.color_palette('dark', n_colors=1))

df['yr']=(df['age']/365).round(0)

df.yr

seaborn.countplot(x='yr', hue='cardio',data=df, palette='colorblind', edgecolor=seaborn.color_palette('dark', n_colors=1))

seaborn.countplot(x='yr', hue='cardio', data=df, palette='colorblind', edgecolor=seaborn.color_palette('dark', n_colors=1))

df.describe()

df.corr()

df

new=df.drop(['yr'], axis=1)

new

y=new.iloc[:,-1]

y

x=new.drop('cardio',axis=1)

x

from sklearn.model_selection import train_test_split

xtrain, xtest, ytrain, ytest=train_test_split(x,y, test_size=.30, random_state=1)

xtrain

from sklearn.ensemble import RandomForestClassifier

rfcl=RandomForestClassifier()

rfcl.fit(xtrain, ytrain)

rfcl.score(xtest, ytest)

from sklearn.tree import DecisionTreeClassifier

dtcf=DecisionTreeClassifier()

dtcf.fit(xtrain, ytrain)

dtcf.score(xtest, ytest)

